const ROOTS = {
    AUTH: '/auth',
    ADMIN: '/admin',
    ACCOUNTANT: '/accountant',
    PARTNER: '/partner',
};

const paths = {
    authPaths: {
        jwt: {
            login: `login`,
            register: `register`,
            logout: `logout`,
        },
        subscription: 'plan',
        lockScreen: 'lock-screen',
        forgotPassword: '/forgot-password',
    },
    userPaths: {
        index: 'dashboard',
        assistant: '/assistant',
        appointments: '/appointments',
        callLogs: '/call-logs',
        calendar: '/calendar',
        account: '/account',
        plans: '/plans',
        checklist: { index: 'checklist', view: 'checklist/:id' },
        expenses: 'expenses',
        invoices: {
            index: 'invoices',
            customers: 'invoices/customers',
            invoiceDetails: 'invoices/:id',
            upload: 'invoices/upload',
            create: 'invoices/create',
            edit: 'invoices/edit/:id',
            view: 'invoices/view/:id',
        },
        reports: 'reports',
        taxFiling: { index: 'tax-filing/recent', previous: 'tax-filing/previous' },
        cfoServices: {
            index: 'cfo-services',
            myRequests: 'cfo-services/my-requests',
            viewMyRequests: 'cfo-services/my-requests/:id',
        },
        vendorPayments: {
            index: 'vendor-payments',
            uploadBill: 'vendor-payments/upload-bill',
            vendors: 'vendor-payments/vendors',
            edit: 'vendor-payments/edit/:id',
            view: 'vendor-payments/view/:id',
        },
        salaries: 'salaries',
        reconcile: 'reconcile',
        chat: 'chat',
        settings: {
            profile: 'settings/profile',
            changePassword: 'settings/change-password',
            myPlans: 'settings/my-plans',
            software: 'settings/softwares',
            support: 'settings/support',
            passwords: 'settings/my-passwords',
            alerts: 'settings/alerts',
            referal: 'settings/referral',
        },
        formDemo: 'form-demo',
        formValidation: 'form-validation',
        bookMeetings: 'book-a-meeting',
        meetings: {
            index: 'meetings/schedule',
            calendar: 'meetings/calendar',
            view: 'meetings/schedule/:id',
        },
        compliances: {
            vat: 'vat',
            corporateTax: 'corporate-tax',
        },
        calender: 'calender',
        notifications: 'notifications',
        messages: 'chat',
        softwares: 'softwares',
        subscription: 'subscription',
        documents: 'documents',
        employees: 'employees',
    },
    adminPaths: {
        index: `${ROOTS.ADMIN}/dashboard`,
        tax: `${ROOTS.ADMIN}/tax`,
        user: `${ROOTS.ADMIN}/users`,
        addUser: `${ROOTS.ADMIN}/add-user`,
        // profile: `${ROOTS.ADMIN}/profile`,
        settings: {
            profile: 'admin/settings/profile',
            changePassword: 'admin/settings/change-password',
        },
        notificationManagement: `${ROOTS.ADMIN}/notification-management`,
        notifications: `${ROOTS.ADMIN}/notifications`,
        grievances: `${ROOTS.ADMIN}/grievances`,
        services: `${ROOTS.ADMIN}/services`,
        subscription: {
            index: `${ROOTS.ADMIN}/subscription/plans`,
            partnerPlans: `${ROOTS.ADMIN}/subscription/plans/partner`,
            coupons: `${ROOTS.ADMIN}/subscription/coupons`,
        },
        reminders: `${ROOTS.ADMIN}/reminders`,
        roles: `${ROOTS.ADMIN}/roles`,
        support: `${ROOTS.ADMIN}/support`,
        settlements: `${ROOTS.ADMIN}/settlements`,
    },
    partnerPaths: {
        index: `${ROOTS.PARTNER}/dashboard`,
        // profile: `${ROOTS.PARTNER}/profile`,
        settings: {
            profile: `${ROOTS.PARTNER}/settings/profile`,
            changePassword: `${ROOTS.PARTNER}/settings/change-password`,
        },
        users: `${ROOTS.PARTNER}/users`,

        accountants: `${ROOTS.PARTNER}/accountants`,
        apiDocumentation: `${ROOTS.PARTNER}/api-documentation`,
        ledger: `${ROOTS.PARTNER}/ledger`,
        calender: `${ROOTS.PARTNER}/calender`,
        reminders: `${ROOTS.PARTNER}/notifications`,
        grievances: `${ROOTS.PARTNER}/grievances`,
        invoices: `${ROOTS.PARTNER}/invoices`,
        messaging: `${ROOTS.PARTNER}/messaging`,
        clients: `${ROOTS.PARTNER}/clients`,
        apiKey: `${ROOTS.PARTNER}/api-key`,
        ipAdresses: `${ROOTS.PARTNER}/ip-addresses`,
        notifications: `${ROOTS.PARTNER}/notifications`,
        notificationMangement: `${ROOTS.PARTNER}/notification-management`,
        settlements: `${ROOTS.PARTNER}/settlements`,
    },
    accountantPaths: {
        index: `${ROOTS.ACCOUNTANT}/dashboard`,
        checklist: {
            view: `${ROOTS.ACCOUNTANT}/checklist/:id`,
            index: `${ROOTS.ACCOUNTANT}/checklist`,
        },
        reports: `${ROOTS.ACCOUNTANT}/reports`,
        bookkeeping: `${ROOTS.ACCOUNTANT}/clients/book-keeping`,
        // profile: `${ROOTS.ACCOUNTANT}/profile`,
        settings: {
            profile: `${ROOTS.ACCOUNTANT}/settings/profile`,
            changePassword: `${ROOTS.ACCOUNTANT}/settings/change-password`,
        },
        ledger: `${ROOTS.ACCOUNTANT}/ledger`,
        calender: `${ROOTS.ACCOUNTANT}/calender`,
        reminders: `${ROOTS.ACCOUNTANT}/notifications`,
        grievances: `${ROOTS.ACCOUNTANT}/grievances`,
        chat: `${ROOTS.ACCOUNTANT}/chat`,
        salaries: `${ROOTS.ACCOUNTANT}/salaries`,
        meetings: {
            index: `${ROOTS.ACCOUNTANT}/meetings`,
            view: `${ROOTS.ACCOUNTANT}/meetings/:id`,
        },
        messages: `${ROOTS.ACCOUNTANT}/chat`,
        account: `${ROOTS.ACCOUNTANT}/account`,
        expenses: `${ROOTS.ACCOUNTANT}/expenses`,
        invoices: {
            index: `${ROOTS.ACCOUNTANT}/invoices`,
            // edit: `${ROOTS.ACCOUNTANT}/invoices/edit/:id`,
            preview: `${ROOTS.ACCOUNTANT}/invoices/:id`,
        },
        inbox: {
            index: `${ROOTS.ACCOUNTANT}/inbox`,
            processInbox: `${ROOTS.ACCOUNTANT}/inbox/:id`,
        },
        notifications: `${ROOTS.ACCOUNTANT}/notifications`,
        clients: `${ROOTS.ACCOUNTANT}/clients`,
        taxFiling: `${ROOTS.ACCOUNTANT}/tax-filing`,
        reconcile: `${ROOTS.ACCOUNTANT}/reconcile`,
        vendorPayments: {
            index: `${ROOTS.ACCOUNTANT}/vendor-payments`,
            uploadBill: `${ROOTS.ACCOUNTANT}/vendor-payments/upload-bill`,
            vendors: `${ROOTS.ACCOUNTANT}/vendor-payments/vendors`,
            // edit: `${ROOTS.ACCOUNTANT}/vendor-payments/edit/:id`,
            preview: `${ROOTS.ACCOUNTANT}/vendor-payments/:id`,
        },
    },
};

export default paths;
